server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:postgresql://training-db.cqnsz9u6mm7d.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=project-2
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    jackson:
      serialization:
        fail-on-empty-beans: false